name: Metrics
on:
  # Update Daily
  schedule: [{cron: "0 0 * * *"}]
  # Run manually if needed
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: zoe-zentner
          template: classic
          base: header, activity, community, repositories, metadata
          
          # This enables the language stats
          plugin_languages: yes
          
          # "Indepth" is REQUIRED to count languages in forks
          plugin_languages_indepth: yes
          
          # This ensures it scans forks
          repositories_forks: yes
          
          # This ensures it counts YOUR lines, not the whole group project
          commits_authoring: zoe-zentner
          
          # Optional: Ignore common non-code languages
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
