- uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # 1. CHANGE TEMPLATE: This is the key to the compact layout
          template: repository
          base: "" 
          
          # 2. LANGUAGE BAR ONLY: Mimics your first screenshot
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # 3. INCLUDE FORKS: Looks deep into your forked repos
          plugin_languages_indepth: yes
          repositories_forks: yes
          
          # 4. CLEANUP: Hides tiny languages to keep the bar clean
          plugin_languages_threshold: 2%
          plugin_languages_ignored: html, css
